# Generated by Django 3.0.2 on 2020-01-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20200128_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='aaa', max_length=20),
            preserve_default=False,
        ),
    ]
